---
all:
  children:
    ubuntu:
      children:
        ubuntu2404_builders:
          hosts:
            ubuntu2404-staging-01:
              ansible_host: 192.168.1.100
              ansible_user: testuser
              ansible_ssh_private_key_file: ~/.ssh/id_rsa_staging
              ansible_become_method: sudo

        ubuntu2404_agents:
          hosts:
            agent-staging-01:
              ansible_host: 192.168.1.110
              ansible_user: testuser
              ansible_ssh_private_key_file: ~/.ssh/id_rsa_staging
              ansible_become_method: sudo
              azp_agent_instances:
                - { name: "staging-agent-01" }
